### ISSUE TITLE
Should this be moved to the msr-neutronics repository?

### ISSUE THREAD

**Issue by katyhuff** [arfc/serpent-input#1]
This issue can be closed when either:

1. It is decided this repository should remain here.

or 

2. The contents of this repository have been moved (with git history intact!) into the msr-neutronics repository, and deleted.

note, it's possible this stuff is already there... someone could perhaps check?

**Comment by ZoeRichter** [comment]
I looked through both repositories:

In arfc/serpent-input, there is an "alex-candu" directory for CANDU reactors that might not fit in an msr repository.
As far as contents, it looks like the last updates to arfc/serpent-input's contents were 2 years ago, and it doesn't appear as though any files are direct copies of each other.

**Comment by ZoeRichter** [comment]
I just made a pull request to msr-neutronics to move the two msr directories from here to there.
